{% set name = "zlogging" %}
{% set version = environ['zlogging_VERSION'] %}
{% set build_number = environ['zlogging_BUILD'] %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ../..
  #git_url: https://github.com/JarryShaw/zlogging.git
  #git_rev: "conda-{{ version }}+{{ build_number }}"
  #git_depth: 1 # (Defaults to -1/not shallow)

build:
  number: {{ build_number }}
  entry_points:
    - zlogging-gen = zlogging._gen:main
  #script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - git
    - python
    - pip
    - setuptools>=61.0.0
  host:
    - python
    - pip
    - setuptools>=61.0.0
  run:
    - python

test:
 imports:
   - zlogging

about:
  home: https://jarryshaw.github.io/zlogging
  license: BSD 3-Clause License
  license_family: BSD
  license_file:
    - LICENSE
  summary: "ZLogging: Bro/Zeek logging framework for Python."
  doc_url: https://jarryshaw.github.io/Zlogging
  dev_url: https://github.com/jarryshaw/zlogging

extra:
  recipe-maintainers:
    - jarryshaw
